# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: dpbench-dev
channels:
  - dppy/label/dev
  - conda-forge
  - intel
  - nodefaults
dependencies:
  - pip
  - tomli
  - alembic
  - sqlalchemy
  - py-cpuinfo
  - scipy
  - scikit-learn
  - pandas
  - intel::numpy
  - numba
  - dpctl
  - dpnp
  - numba-dpex
  - numba-mlir
