name: build and run

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build_linux:
    name: Builds dpbench and runs the benchmarks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.8", "3.9"]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout dpbench
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python }}
          activate-environment: dpbench-devel

      - name: Conda info
        shell: bash -l {0}
        run: conda info

      - name: Install dpbench dependencies
        shell: bash -l {0}
        run: |
          conda install numpy numba
          conda list

      - name: Build dpbench
        shell: bash -l {0}
        run: |
          python setup.py develop

      - name: Validate dpbench
        shell: bash -l {0}
        run: |
          python -c "import dpbench; dpbench.run_benchmarks()" || exit 1
